#ifndef RT3DUS_DEFINITIONS_H
#define RT3DUS_DEFINITIONS_H

enum REND_SLIDER_CODES
{
    REND_SLIDER_X = 0,
    REND_SLIDER_Y,
    REND_SLIDER_Z,
    REND_SLIDER_DEN,
    REND_SLIDER_BRI,
    REND_SLIDER_TFR_OFF,
    REND_SLIDER_TFR_SCL,
    REND_SLIDER_LO_THRESH,
    REND_SLIDER_HI_THRESH,
    REND_SLIDER_LINFILT
};

#endif // RT3DUS_DEFINITIONS_H
